DROP TABLE IF EXISTS dishes;
CREATE TABLE dishes (
    id SERIAL PRIMARY KEY,
    name TEXT,
    fat_level TEXT,
    fiber_level TEXT,
    protein_level TEXT,
    sodium_level TEXT,
    score CHAR(1),
    preparation_method TEXT,
    dish_type TEXT,
    diet_type TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
BEGIN;



INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (1, 'Soupe de légumes', 'low', 'medium', 'low', 'medium', 'B', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (2, 'Velouté de potiron', 'medium', 'medium', 'low', 'medium', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (3, 'Soupe à l''oignon', 'low', 'high', 'low', 'medium', 'B', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (4, 'Salade de quinoa', 'low', 'high', 'low', 'low', 'A', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (5, 'Salade de lentilles', 'low', 'high', 'low', 'low', 'A', 'raw', 'salad', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (6, 'Salade niçoise', 'medium', 'high', 'medium', 'medium', 'B', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (7, 'Carottes râpées', 'low', 'high', 'low', 'low', 'B', 'boiled', 'main dish', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (8, 'Taboulé', 'low', 'high', 'low', 'low', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (9, 'Betteraves vinaigrette', 'low', 'high', 'low', 'low', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (10, 'Crudités variées', 'low', 'high', 'low', 'low', 'A', 'raw', 'salad', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (11, 'Bruschetta', 'medium', 'medium', 'low', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (12, 'Gaspacho', 'low', 'high', 'low', 'low', 'B', 'boiled', 'soup', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (13, 'Soupe miso', 'low', 'medium', 'medium', 'high', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (14, 'Soupe Tom Yum', 'low', 'medium', 'medium', 'high', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (15, 'Salade César', 'medium', 'high', 'medium', 'medium', 'B', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (16, 'Salade grecque', 'low', 'high', 'low', 'medium', 'B', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (17, 'Salade caprese', 'low', 'medium', 'low', 'low', 'B', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (18, 'Salade russe', 'medium', 'medium', 'low', 'medium', 'C', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (19, 'Houmous', 'medium', 'high', 'medium', 'medium', 'B', 'raw', 'starter', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (20, 'Caviar d''aubergine', 'medium', 'high', 'low', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (21, 'Oeufs mimosa', 'low', 'medium', 'medium', 'low', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (22, 'Caponata', 'medium', 'high', 'low', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (23, 'Gyoza', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (24, 'Satay de poulet', 'medium', 'low', 'medium', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (25, 'Yakitori de poulet', 'medium', 'low', 'medium', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (26, 'Calamars frits', 'high', 'low', 'low', 'high', 'E', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (27, 'Nachos', 'high', 'low', 'low', 'high', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (28, 'Velouté de champignons', 'medium', 'medium', 'low', 'medium', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (29, 'Bisque de homard', 'medium', 'low', 'medium', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (30, 'Potage Parmentier', 'low', 'medium', 'low', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (31, 'Salade de chèvre chaud', 'medium', 'medium', 'medium', 'medium', 'C', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (32, 'Blinis au saumon fumé', 'medium', 'low', 'medium', 'medium', 'C', 'steamed', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (33, 'Ceviche de poisson', 'low', 'low', 'high', 'medium', 'A', 'raw', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (34, 'Carpaccio de boeuf', 'low', 'low', 'high', 'medium', 'B', 'raw', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (35, 'Melon au jambon cru', 'low', 'medium', 'medium', 'medium', 'C', 'raw', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (36, 'Rouleaux de printemps', 'low', 'medium', 'low', 'medium', 'C', 'raw', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (37, 'Nems', 'high', 'low', 'low', 'high', 'E', 'fired', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (38, 'Samosas', 'high', 'low', 'low', 'high', 'E', 'fried', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (39, 'Tempura de crevettes', 'high', 'low', 'medium', 'medium', 'D', 'fried', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (40, 'Pakoras de légumes', 'high', 'medium', 'low', 'medium', 'D', 'boiled', 'main dish', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (41, 'Feuilles de vigne farcies', 'low', 'high', 'low', 'low', 'B', 'raw', 'starter', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (42, 'Arancini au boeuf', 'high', 'low', 'low', 'medium', 'D', 'fried', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (43, 'Croquettes de pommes de terre', 'high', 'low', 'low', 'medium', 'D', 'fried', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (44, 'Patatas bravas', 'high', 'low', 'low', 'high', 'F', 'fried', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (45, 'Gambas à l''ail', 'medium', 'low', 'medium', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (46, 'Tortilla espagnole', 'medium', 'medium', 'medium', 'medium', 'C', 'fried', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (47, 'Empanadas', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (48, 'Guacamole', 'medium', 'medium', 'low', 'medium', 'C', 'raw', 'starter', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (49, 'Baba ganoush', 'medium', 'high', 'low', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (50, 'Brie au four', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (51, 'Salade de papaye verte', 'low', 'high', 'low', 'low', 'B', 'raw', 'salad', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (52, 'Salade de chou (coleslaw)', 'medium', 'medium', 'low', 'medium', 'C', 'raw', 'salad', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (53, 'Antipasto italien', 'medium', 'medium', 'medium', 'medium', 'C', 'boiled', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (54, 'Salade de pommes de terre', 'low', 'medium', 'low', 'medium', 'C', 'raw', 'salad', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (55, 'Salade de poulpe', 'low', 'medium', 'high', 'medium', 'B', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (56, 'Soupe minestrone', 'low', 'medium', 'low', 'medium', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (57, 'Soupe de poisson', 'low', 'medium', 'medium', 'medium', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (58, 'Soupe à la tomate', 'low', 'medium', 'low', 'medium', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (59, 'Soupe de pois cassés', 'low', 'high', 'medium', 'medium', 'B', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (60, 'Quiche lorraine', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (61, 'Tarte flambée', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (62, 'Salade d''algues', 'low', 'high', 'low', 'low', 'B', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (63, 'Edamame', 'low', 'high', 'low', 'low', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (64, 'Tzatziki', 'low', 'medium', 'low', 'medium', 'C', 'raw', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (65, 'Soupe wonton', 'low', 'low', 'medium', 'high', 'D', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (66, 'Tom Kha Kai', 'medium', 'medium', 'medium', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (67, 'Salade Waldorf', 'medium', 'medium', 'medium', 'medium', 'C', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (68, 'Soupe aux asperges', 'low', 'medium', 'low', 'medium', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (69, 'Consommé de boeuf', 'low', 'low', 'medium', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (70, 'Accras de morue', 'high', 'low', 'low', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (71, 'Ailes de poulet épicées', 'high', 'low', 'medium', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (72, 'Quesadillas au fromage', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (73, 'Spanakopita', 'high', 'medium', 'low', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (74, 'Raviolis vapeur', 'low', 'low', 'medium', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (75, 'Camembert rôti', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (76, 'Beignets de banane plantain', 'high', 'low', 'low', 'medium', 'D', 'fried', 'snack', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (77, 'Plantains frits', 'high', 'low', 'low', 'high', 'E', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (78, 'Salade de gésiers', 'medium', 'medium', 'medium', 'medium', 'C', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (79, 'Foie gras sur toast', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (80, 'Escargots à la bourguignonne', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (81, 'Plateau d''huîtres', 'low', 'high', 'low', 'low', 'A', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (82, 'Salade méchouia', 'low', 'high', 'low', 'low', 'A', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (83, 'Soupe de lentilles', 'low', 'high', 'medium', 'medium', 'B', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (84, 'Velouté de courgette', 'medium', 'high', 'low', 'medium', 'C', 'boiled', 'soup', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (85, 'Salade de fruits de mer', 'low', 'high', 'low', 'low', 'B', 'raw', 'salad', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (86, 'Salade de crabe', 'low', 'medium', 'medium', 'medium', 'C', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (87, 'Galettes de courgette', 'medium', 'high', 'low', 'medium', 'C', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (88, 'Croquettes de jambon', 'high', 'low', 'medium', 'high', 'F', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (89, 'Bouchées à la reine', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (90, 'Salade Cobb', 'medium', 'high', 'medium', 'medium', 'B', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (91, 'Cocktail de crevettes', 'low', 'low', 'high', 'medium', 'A', 'boiled', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (92, 'Oeuf cocotte', 'medium', 'low', 'medium', 'medium', 'C', 'boiled', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (93, 'Pâté de campagne', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (94, 'Salade de thon', 'medium', 'medium', 'medium', 'medium', 'C', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (95, 'Bourek', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (96, 'Beignets d''oignon', 'high', 'high', 'low', 'high', 'E', 'fried', 'snack', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (97, 'Pissaladière', 'high', 'low', 'low', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (98, 'Salade de roquette au parmesan', 'medium', 'medium', 'low', 'medium', 'C', 'raw', 'salad', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (99, 'Brik à l''oeuf', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'starter', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (100, 'Salade méchouia', 'low', 'high', 'low', 'low', 'A', 'raw', 'salad', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (101, 'Poulet rôti', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (102, 'Blanquette de veau', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (103, 'Boeuf bourguignon', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (104, 'Rôti de porc', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (105, 'Escalope de dinde', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (106, 'Saumon grillé', 'low', 'medium', 'high', 'medium', 'A', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (107, 'Cabillaud vapeur', 'low', 'medium', 'high', 'medium', 'B', 'steamed', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (108, 'Spaghetti bolognaise', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (109, 'Lasagnes', 'high', 'low', 'high', 'medium', 'D', 'baked', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (110, 'Brandade de morue', 'high', 'medium', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (111, 'Tian de légumes', 'low', 'high', 'low', 'low', 'B', 'boiled', 'main dish', 'vegan', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (112, 'Ratatouille', 'low', 'high', 'low', 'low', 'A', 'boiled', 'main dish', 'vegan', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (113, 'Hachis parmentier', 'high', 'low', 'high', 'medium', 'E', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (114, 'Pizza quatre fromages', 'high', 'low', 'high', 'high', 'F', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (115, 'Tartiflette', 'high', 'low', 'medium', 'high', 'F', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (116, 'Cassoulet', 'high', 'medium', 'high', 'high', 'F', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (117, 'Choucroute garnie', 'high', 'medium', 'high', 'high', 'F', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (118, 'Burger au fromage', 'high', 'low', 'high', 'high', 'D', 'grilled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (119, 'Wrap au poulet', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (120, 'Steak frites', 'high', 'low', 'high', 'high', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (121, 'Magret de canard', 'high', 'low', 'high', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (122, 'Confit de canard', 'high', 'low', 'high', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (123, 'Coq au vin', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (124, 'Bouillabaisse', 'low', 'medium', 'high', 'high', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (125, 'Pot-au-feu', 'low', 'medium', 'high', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (126, 'Pizza Margherita', 'high', 'low', 'medium', 'high', 'D', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (127, 'Risotto aux champignons', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (128, 'Spaghetti carbonara', 'high', 'low', 'high', 'high', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (129, 'Osso buco', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (130, 'Parmigiana d''aubergines', 'high', 'medium', 'low', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (131, 'Paella', 'medium', 'medium', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (132, 'Pulpo a la gallega', 'low', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (133, 'Cochinillo', 'high', 'medium', 'high', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (134, 'Fajitas au poulet', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (135, 'Chili con carne', 'medium', 'medium', 'high', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (136, 'Moussaka', 'high', 'low', 'high', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (137, 'Gyros', 'high', 'low', 'high', 'high', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (138, 'Souvlaki d''agneau', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (139, 'Couscous royal', 'medium', 'medium', 'high', 'high', 'A', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (140, 'Tajine de poulet au citron', 'medium', 'medium', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (141, 'Shawarma', 'high', 'low', 'high', 'high', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (142, 'Poulet Yassa', 'medium', 'medium', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (143, 'Mafé (ragoût d''arachide)', 'high', 'medium', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (144, 'Thiéboudiène', 'medium', 'medium', 'high', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (145, 'Riz Jollof', 'medium', 'medium', 'medium', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (146, 'Poulet moambé', 'medium', 'medium', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (147, 'Assortiment de sushis', 'low', 'low', 'high', 'low', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (148, 'Ramen au boeuf', 'medium', 'low', 'high', 'high', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (149, 'Pad thaï', 'medium', 'medium', 'medium', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (150, 'Curry vert thaï', 'high', 'medium', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (151, 'Pho au boeuf', 'low', 'low', 'high', 'high', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (152, 'Bibimbap', 'medium', 'medium', 'high', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (153, 'Biryani au poulet', 'medium', 'medium', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (154, 'Poulet tikka masala', 'high', 'medium', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (155, 'Curry de légumes', 'low', 'high', 'low', 'medium', 'B', 'boiled', 'main dish', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (156, 'Tofu sauté aux légumes', 'low', 'high', 'low', 'medium', 'B', 'sautéed', 'main dish', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (157, 'Canard laqué', 'high', 'low', 'high', 'high', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (158, 'Porc au caramel', 'high', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (159, 'Poulet Général Tao', 'high', 'low', 'high', 'high', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (160, 'Boeuf aux oignons', 'medium', 'high', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (161, 'Dal de lentilles', 'low', 'high', 'medium', 'low', 'A', 'boiled', 'main dish', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (162, 'Curry de poisson', 'high', 'medium', 'high', 'medium', 'C', 'steamed', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (163, 'Fish and chips', 'high', 'low', 'medium', 'high', 'E', 'fried', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (164, 'Escalope viennoise', 'high', 'low', 'high', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (165, 'Steak tartare', 'low', 'low', 'high', 'medium', 'B', 'raw', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (166, 'Pizza hawaïenne', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (167, 'Tourtière', 'high', 'low', 'high', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (168, 'Côte de boeuf grillée', 'low', 'low', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (169, 'Brochettes de poulet', 'low', 'low', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (170, 'Poulet basquaise', 'medium', 'medium', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (171, 'Gratin de pâtes au jambon', 'high', 'low', 'medium', 'medium', 'D', 'gratinated', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (172, 'Macaronis au fromage', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (173, 'Penne all''arrabbiata', 'low', 'low', 'low', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (174, 'Burger végétarien', 'high', 'medium', 'medium', 'high', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (175, 'Poutine', 'high', 'low', 'low', 'high', 'F', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (176, 'Club sandwich', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (177, 'Burrito au boeuf', 'high', 'low', 'high', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (178, 'Enchiladas au poulet', 'high', 'low', 'high', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (179, 'Ragoût irlandais', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (180, 'Curry japonais', 'high', 'low', 'high', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (181, 'Okonomiyaki', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (182, 'Carbonade flamande', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (183, 'Waterzooi de poulet', 'medium', 'medium', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (184, 'Pizza aux légumes grillés', 'high', 'medium', 'low', 'medium', 'C', 'baked', 'main dish', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (185, 'Jambalaya', 'medium', 'medium', 'high', 'high', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (186, 'Cordon bleu', 'high', 'low', 'high', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (187, 'Filet mignon sauce champignons', 'medium', 'medium', 'high', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (188, 'Boeuf Stroganoff', 'medium', 'low', 'high', 'medium', 'B', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (189, 'Travers de porc barbecue', 'high', 'low', 'high', 'high', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (190, 'Curry d''agneau', 'high', 'low', 'high', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (191, 'Boulettes de viande suédoises', 'high', 'low', 'high', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (192, 'Goulash', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (193, 'Sandwich kebab', 'high', 'low', 'high', 'high', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (194, 'Shakshuka', 'medium', 'medium', 'medium', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (195, 'Fondue savoyarde', 'high', 'low', 'high', 'high', 'F', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (196, 'Raclette', 'high', 'low', 'high', 'high', 'F', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (197, 'Boeuf Wellington', 'high', 'low', 'high', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (198, 'Homard Thermidor', 'high', 'low', 'medium', 'medium', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (199, 'Pizza pepperoni', 'high', 'low', 'medium', 'high', 'D', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (200, 'Omelette aux fines herbes', 'medium', 'low', 'medium', 'medium', 'C', 'fried', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (201, 'Compote de pommes', 'low', 'high', 'low', 'low', 'A', 'baked', 'dessert', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (202, 'Yaourt nature', 'low', 'low', 'medium', 'low', 'A', 'raw', 'dessert', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (203, 'Fruit frais', 'low', 'high', 'low', 'low', 'A', 'raw', 'dessert', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (205, 'Crème dessert', 'medium', 'low', 'low', 'low', 'C', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (206, 'Tarte aux pommes', 'high', 'medium', 'low', 'low', 'D', 'baked', 'dessert', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (207, 'Gâteau au yaourt', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (208, 'Riz au lait', 'medium', 'low', 'low', 'low', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (209, 'Moelleux au chocolat', 'high', 'low', 'medium', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (210, 'Île flottante', 'high', 'low', 'low', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (211, 'Crème brûlée', 'high', 'low', 'medium', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (212, 'Mousse au chocolat', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (213, 'Profiteroles', 'high', 'low', 'low', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (214, 'Éclair au chocolat', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (215, 'Macarons', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (216, 'Crêpes Suzette', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (217, 'Tarte Tatin', 'high', 'medium', 'low', 'low', 'D', 'baked', 'dessert', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (218, 'Charlotte aux fraises', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (219, 'Paris-Brest', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (220, 'Mille-feuille', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (221, 'Galette des rois', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (222, 'Fondant au chocolat', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (223, 'Tiramisu', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (224, 'Panna cotta', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (225, 'Cheesecake', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (226, 'Brownie', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (227, 'Donut glacé', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (228, 'Churros', 'high', 'low', 'low', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (229, 'Flan caramel', 'medium', 'low', 'medium', 'low', 'C', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (230, 'Baklava', 'high', 'low', 'low', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (231, 'Gulab jamun', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (232, 'Mochi', 'medium', 'low', 'low', 'low', 'C', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (233, 'Cake au citron', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (234, 'Cupcake à la vanille', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (235, 'Pavlova', 'medium', 'low', 'low', 'low', 'C', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (236, 'Trifle anglais', 'high', 'low', 'low', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (237, 'Crumble aux pommes', 'high', 'medium', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (238, 'Gaufres au sucre', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (239, 'Beignets', 'high', 'low', 'low', 'low', 'D', 'fried', 'snack', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (240, 'Tarte au citron meringuée', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (241, 'Glace à la vanille', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (242, 'Sorbet au citron', 'low', 'high', 'low', 'low', 'B', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (243, 'Poire Belle-Hélène', 'high', 'low', 'low', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (244, 'Banana split', 'high', 'low', 'low', 'low', 'D', 'frozen', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (245, 'Café liégeois', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (246, 'Crêpe au sucre', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (247, 'Pain perdu', 'high', 'low', 'medium', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (248, 'Baba au rhum', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (249, 'Nougat glacé', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (250, 'Far Breton', 'high', 'low', 'medium', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (251, 'Tarte au chocolat', 'high', 'low', 'medium', 'low', 'D', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (252, 'Forêt-Noire', 'high', 'low', 'medium', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (253, 'Strudel aux pommes', 'high', 'high', 'low', 'low', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (254, 'Sachertorte', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (255, 'Chausson aux pommes', 'high', 'medium', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (256, 'Madeleines', 'high', 'low', 'medium', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (257, 'Panettone', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (258, 'Canelé', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (259, 'Crème caramel', 'medium', 'low', 'medium', 'low', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (260, 'Fondue au chocolat', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (261, 'Tarte aux fraises', 'high', 'low', 'low', 'low', 'D', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (262, 'Tarte au fromage blanc', 'high', 'low', 'medium', 'low', 'D', 'baked', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (263, 'Mont blanc (dessert)', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (264, 'Pudding au pain', 'high', 'low', 'medium', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (265, 'Clafoutis aux cerises', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (266, 'Sorbet à la mangue', 'low', 'high', 'low', 'low', 'B', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (267, 'Glace au chocolat', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (268, 'Carrot cake', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (269, 'Tarte à la rhubarbe', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (270, 'Parfait glacé', 'medium', 'low', 'low', 'low', 'C', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (271, 'Knafeh', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (272, 'Crème glacée à la pistache', 'high', 'low', 'low', 'low', 'D', 'boiled', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (273, 'Flan coco', 'medium', 'low', 'medium', 'low', 'C', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (274, 'Pastel de nata', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (275, 'Yaourt glacé', 'medium', 'low', 'medium', 'low', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (276, 'Mousse de fraise', 'medium', 'low', 'low', 'low', 'C', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (277, 'Compote de pêches', 'low', 'high', 'low', 'low', 'B', 'baked', 'dessert', 'vegan', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (278, 'Gâteau au chocolat', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (279, 'Truffes au chocolat', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (280, 'Sorbet à la fraise', 'low', 'high', 'low', 'low', 'B', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (281, 'Bûche de Noël', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (282, 'Dame Blanche', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (283, 'Sabayon au Marsala', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (284, 'Beignet aux pommes', 'high', 'low', 'low', 'low', 'D', 'fried', 'snack', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (285, 'Donut au chocolat', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (286, 'Kulfi à la pistache', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (287, 'Riz gluant à la mangue', 'medium', 'medium', 'low', 'low', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (288, 'Ananas rôti', 'low', 'high', 'low', 'low', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (289, 'Granité au café', 'low', 'low', 'low', 'low', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (290, 'Mousse au citron', 'medium', 'low', 'low', 'low', 'C', 'baked', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (291, 'Banoffee pie', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (293, 'Sabayon au Marsala', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (295, 'Dame Blanche', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (296, 'Sabayon au Marsala', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (297, 'Omelette norvégienne', 'high', 'low', 'low', 'low', 'D', 'frozen', 'dessert', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (298, 'Cannoli', 'medium', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (299, 'Sabayon au Marsala', 'high', 'low', 'low', 'low', 'D', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (300, 'Glace menthe-chocolat', 'high', 'low', 'low', 'low', 'D', 'frozen', 'dessert', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (301, 'Croque monsieur', 'medium', 'low', 'medium', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (302, 'Hot Dog', 'high', 'low', 'medium', 'high', 'D', 'grilled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (303, 'Croissant', 'high', 'low', 'low', 'medium', 'D', 'baked', 'snack', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (304, 'Bobun de poulet', 'medium', 'medium', 'high', 'medium', 'B', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (305, 'Bobun végétarien', 'low', 'high', 'medium', 'medium', 'A', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (306, 'Sandwich Jambon Beurre', 'medium', 'low', 'medium', 'medium', 'C', 'raw', 'snack', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (307, 'Tomates farcies', 'medium', 'medium', 'high', 'medium', 'C', 'baked', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (308, 'Pâtes au beurre', 'high', 'low', 'low', 'medium', 'D', 'boiled', 'main dish', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (309, 'Brioche au beurre', 'high', 'low', 'low', 'medium', 'D', 'baked', 'snack', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (310, 'Poulet frit', 'high', 'low', 'high', 'high', 'D', 'fried', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (311, 'Pain blanc', 'low', 'low', 'low', 'low', 'B', 'baked', 'snack', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (312, 'Pain complet', 'low', 'high', 'low', 'low', 'A', 'baked', 'snack', 'vegetarian', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) VALUES (313, 'Ravioli au boeuf', 'medium', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());
INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (314, 'Pain de seigle', 'low', 'high', 'low', 'low', 'A', 'baked', 'snack', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (315, 'Pain aux olives', 'medium', 'medium', 'low', 'medium', 'B', 'baked', 'snack', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (316, 'Pain épeautre', 'low', 'high', 'low', 'low', 'A', 'baked', 'snack', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (317, 'Granola', 'medium', 'high', 'low', 'low', 'B', 'raw', 'snack', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (318, 'Tartine de Nutella', 'high', 'low', 'low', 'medium', 'D', 'raw', 'snack', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (319, 'Muesli fruits rouges', 'low', 'high', 'low', 'low', 'A', 'raw', 'snack', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (321, 'Pâtes à la sauce tomate', 'low', 'low', 'low', 'medium', 'B', 'boiled', 'main dish', 'vegan', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (322, 'Pâtes au pesto', 'medium', 'low', 'medium', 'medium', 'C', 'boiled', 'main dish', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (323, 'Riz cantonais', 'medium', 'low', 'medium', 'medium', 'C', 'fried', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (324, 'Nouilles de riz', 'low', 'low', 'medium', 'medium', 'B', 'boiled', 'main dish', 'vegan', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (325, 'Tarte aux daims', 'high', 'low', 'low', 'medium', 'D', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (326, 'Tacos français', 'medium', 'low', 'medium', 'medium', 'E', 'grilled', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (327, 'Burrito au poulet', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (328, 'Burger au poisson', 'medium', 'low', 'high', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (329, 'Pokebowl', 'low', 'high', 'medium', 'low', 'B', 'raw', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (330, 'Roulés à la cannelle', 'high', 'low', 'low', 'medium', 'D', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (331, 'Pizza Reine', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (332, 'Flammenkuche', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (333, 'Quiche saumon épinards', 'medium', 'medium', 'high', 'medium', 'C', 'baked', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (334, 'Galette saucisse', 'medium', 'low', 'high', 'medium', 'D', 'grilled', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (335, 'Galette complète', 'medium', 'low', 'medium', 'medium', 'C', 'grilled', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (336, 'Crêpe Nutella', 'high', 'low', 'low', 'medium', 'D', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (337, 'Moules frites', 'low', 'low', 'high', 'medium', 'C', 'boiled', 'main dish', 'omnivore', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (338, 'Cake aux olives', 'high', 'low', 'medium', 'medium', 'C', 'baked', 'starter', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (339, 'Bruschetta tomate-basilic', 'low', 'medium', 'low', 'low', 'B', 'grilled', 'starter', 'vegan', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (340, 'Brioche perdue', 'high', 'low', 'medium', 'medium', 'D', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (341, 'Tarte aux poires', 'high', 'medium', 'low', 'low', 'C', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (342, 'Verrine de fruits frais', 'low', 'high', 'low', 'low', 'A', 'raw', 'dessert', 'vegan', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (343, 'Gâteau roulé à la confiture', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (344, 'Pavlova aux fruits rouges', 'medium', 'low', 'low', 'low', 'C', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (345, 'Muffin aux myrtilles', 'high', 'low', 'medium', 'low', 'D', 'baked', 'dessert', 'vegetarian', NOW());

INSERT INTO dishes (id, name, fat_level, fiber_level, protein_level, sodium_level, score, preparation_method, dish_type, diet_type, created_at) 
VALUES (346, 'Chou à la crème', 'high', 'low', 'low', 'low', 'D', 'baked', 'dessert', 'vegetarian', NOW());

COMMIT;
