DROP TABLE IF EXISTS songs;
CREATE TABLE songs (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    bpm INTEGER NOT NULL,
    style TEXT,
    apple_music_link TEXT,
    spotify_link TEXT,
    note TEXT,
    created_at TIMESTAMP NOT NULL
);

BEGIN;
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (1, 'Stayin'' Alive', 'Bee Gees', 104, 'disco', 'https://music.apple.com/fr/search?term=Stayin%27%20Alive%20Bee%20Gees', 'https://open.spotify.com/search/Stayin%27%20Alive%20Bee%20Gees', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (2, 'Night Fever', 'Bee Gees', 109, 'disco', 'https://music.apple.com/fr/search?term=Night%20Fever%20Bee%20Gees', 'https://open.spotify.com/search/Night%20Fever%20Bee%20Gees', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (3, 'You Should Be Dancing', 'Bee Gees', 123, 'disco', 'https://music.apple.com/fr/search?term=You%20Should%20Be%20Dancing%20Bee%20Gees', 'https://open.spotify.com/search/You%20Should%20Be%20Dancing%20Bee%20Gees', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (4, 'Jive Talkin''', 'Bee Gees', 106, 'disco', 'https://music.apple.com/fr/search?term=Jive%20Talkin%27%20Bee%20Gees', 'https://open.spotify.com/search/Jive%20Talkin%27%20Bee%20Gees', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (5, 'Hot Stuff', 'Donna Summer', 119, 'disco', 'https://music.apple.com/fr/search?term=Hot%20Stuff%20Donna%20Summer', 'https://open.spotify.com/search/Hot%20Stuff%20Donna%20Summer', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (6, 'I Feel Love', 'Donna Summer', 128, 'disco', 'https://music.apple.com/fr/search?term=I%20Feel%20Love%20Donna%20Summer', 'https://open.spotify.com/search/I%20Feel%20Love%20Donna%20Summer', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (7, 'I Will Survive', 'Gloria Gaynor', 117, 'disco', 'https://music.apple.com/fr/search?term=I%20Will%20Survive%20Gloria%20Gaynor', 'https://open.spotify.com/search/I%20Will%20Survive%20Gloria%20Gaynor', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (8, 'Y.M.C.A.', 'Village People', 127, 'disco', 'https://music.apple.com/fr/search?term=Y.M.C.A.%20Village%20People', 'https://open.spotify.com/search/Y.M.C.A.%20Village%20People', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (9, 'Le Freak', 'Chic', 119, 'disco', 'https://music.apple.com/fr/search?term=Le%20Freak%20Chic', 'https://open.spotify.com/search/Le%20Freak%20Chic', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (10, 'Good Times', 'Chic', 111, 'funk', 'https://music.apple.com/fr/search?term=Good%20Times%20Chic', 'https://open.spotify.com/search/Good%20Times%20Chic', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (11, 'Everybody Dance', 'Chic', 130, 'disco', 'https://music.apple.com/fr/search?term=Everybody%20Dance%20Chic', 'https://open.spotify.com/search/Everybody%20Dance%20Chic', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (12, 'September', 'Earth, Wind & Fire', 126, 'funk', 'https://music.apple.com/fr/search?term=September%20Earth,%20Wind%20&%20Fire', 'https://open.spotify.com/search/September%20Earth,%20Wind%20&%20Fire', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (13, 'Boogie Wonderland', 'Earth, Wind & Fire', 132, 'disco', 'https://music.apple.com/fr/search?term=Boogie%20Wonderland%20Earth,%20Wind%20&%20Fire', 'https://open.spotify.com/search/Boogie%20Wonderland%20Earth,%20Wind%20&%20Fire', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (14, 'Let''s Groove', 'Earth, Wind & Fire', 125, 'funk', 'https://music.apple.com/fr/search?term=Let%27s%20Groove%20Earth,%20Wind%20&%20Fire', 'https://open.spotify.com/search/Let%27s%20Groove%20Earth,%20Wind%20&%20Fire', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (15, 'Celebration', 'Kool & The Gang', 122, 'funk', 'https://music.apple.com/fr/search?term=Celebration%20Kool%20&%20The%20Gang', 'https://open.spotify.com/search/Celebration%20Kool%20&%20The%20Gang', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (16, 'Get Down On It', 'Kool & The Gang', 111, 'funk', 'https://music.apple.com/fr/search?term=Get%20Down%20On%20It%20Kool%20&%20The%20Gang', 'https://open.spotify.com/search/Get%20Down%20On%20It%20Kool%20&%20The%20Gang', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (17, 'Ladies'' Night', 'Kool & The Gang', 116, 'funk', 'https://music.apple.com/fr/search?term=Ladies%27%20Night%20Kool%20&%20The%20Gang', 'https://open.spotify.com/search/Ladies%27%20Night%20Kool%20&%20The%20Gang', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (18, 'That''s the Way (I Like It)', 'KC & The Sunshine Band', 109, 'funk', 'https://music.apple.com/fr/search?term=That%27s%20the%20Way%20(I%20Like%20It)%20KC%20&%20The%20Sunshine%20Band', 'https://open.spotify.com/search/That%27s%20the%20Way%20(I%20Like%20It)%20KC%20&%20The%20Sunshine%20Band', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (19, 'Get Down Tonight', 'KC & The Sunshine Band', 113, 'funk', 'https://music.apple.com/fr/search?term=Get%20Down%20Tonight%20KC%20&%20The%20Sunshine%20Band', 'https://open.spotify.com/search/Get%20Down%20Tonight%20KC%20&%20The%20Sunshine%20Band', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (20, '(Shake, Shake, Shake) Shake Your Booty', 'KC & The Sunshine Band', 112, 'funk', 'https://music.apple.com/fr/search?term=(Shake,%20Shake,%20Shake)%20Shake%20Your%20Booty%20KC%20&%20The%20Sunshine%20Band', 'https://open.spotify.com/search/(Shake,%20Shake,%20Shake)%20Shake%20Your%20Booty%20KC%20&%20The%20Sunshine%20Band', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (21, 'Don''t Stop ''Til You Get Enough', 'Michael Jackson', 120, 'funk', 'https://music.apple.com/fr/search?term=Don%27t%20Stop%20%27Til%20You%20Get%20Enough%20Michael%20Jackson', 'https://open.spotify.com/search/Don%27t%20Stop%20%27Til%20You%20Get%20Enough%20Michael%20Jackson', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (22, 'Rock With You', 'Michael Jackson', 96, 'disco', 'https://music.apple.com/fr/search?term=Rock%20With%20You%20Michael%20Jackson', 'https://open.spotify.com/search/Rock%20With%20You%20Michael%20Jackson', 'Convient pour une marche lente.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (23, 'Wanna Be Startin'' Somethin''', 'Michael Jackson', 122, 'funk', 'https://music.apple.com/fr/search?term=Wanna%20Be%20Startin%27%20Somethin%27%20Michael%20Jackson', 'https://open.spotify.com/search/Wanna%20Be%20Startin%27%20Somethin%27%20Michael%20Jackson', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (24, 'Off the Wall', 'Michael Jackson', 119, 'funk', 'https://music.apple.com/fr/search?term=Off%20the%20Wall%20Michael%20Jackson', 'https://open.spotify.com/search/Off%20the%20Wall%20Michael%20Jackson', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
INSERT INTO songs (id, title, artist, bpm, style, apple_music_link, spotify_link, note, created_at) VALUES (25, 'PYT (Pretty Young Thing)', 'Michael Jackson', 120, 'funk', 'https://music.apple.com/fr/search?term=PYT%20(Pretty%20Young%20Thing)%20Michael%20Jackson', 'https://open.spotify.com/search/PYT%20(Pretty%20Young%20Thing)%20Michael%20Jackson', 'Parfait pour une marche rythmée.', '2025-04-12 05:35:47');
COMMIT;